// Code generated by Slice Machine. DO NOT EDIT.

import Breadcrumbs from './Breadcrumbs';
import ContactForm from './ContactForm';
import Header from './Header';
import Image from './Image';
import Quote from './Quote';
import RichText from './RichText';
import Text from './Text';

export {
	Breadcrumbs,
	ContactForm,
	Header,
	Image,
	Quote,
	RichText,
	Text,
};

export const components = {
	breadcrumbs: Breadcrumbs,
	contact_form: ContactForm,
	header: Header,
	image: Image,
	quote: Quote,
	body: RichText,
	text: Text,
};
